### ISSUE TITLE
🐛 Node Visual Glitch

### ISSUE THREAD

**Issue by SizzinSeal** [AnselChang/Pathogen4#10]
Description

- When zooming in, nodes strech for the entire width of the visible field, but only if they go out of the viewport

![ezgif-4-bc40632857](https://user-images.githubusercontent.com/111480281/229659236-65282112-df46-40e3-91f7-e0cff04231a9.gif)

**Comment by AnselChang** [comment]
Hmm. I'll take a look at this. One thing for sure is that high-res screens are screwing with UI. I gotta fix this. Not too sure what it's doing the node stretch but I'll see if it's related.
