### ISSUE TITLE
Go forward commands do not disappear when nodes are deleted

### ISSUE THREAD

**Issue by EcstaticPilot** [AnselChang/Pathogen4#33]
when you delete a node the turn command disappears but the go forward command remains behind leaving 2 go forward commands in a row. In the image, I started by creating 3 nodes and then deleting the middle one
![image_2023-06-17_113715089](https://github.com/AnselChang/Pathogen4/assets/86859304/4b3c9ee1-2ca2-4926-b6ee-985b963eaedc)

**Comment by AnselChang** [comment]
Yeep forgot to impleement delete, nice one
