### ISSUE TITLE
When the highlight button in the node menu is clicked pathogen crashes

### ISSUE THREAD

**Issue by EcstaticPilot** [AnselChang/Pathogen4#34]
clicking the highlight button of the node menu gives the error message

> AttributeError: 'CommandModel' object has no attribute 'highlight'

**Comment by EcstaticPilot** [comment]
seems like I was on the wrong branch

**Comment by EcstaticPilot** [comment]
turns out it was the right branch

**Comment by AnselChang** [comment]
duplicate of #30
